### ISSUE TITLE
catwalk cannot be installed via home-brew

### ISSUE THREAD

**Issue by GenShibe** [catppuccin/homebrew-tap#12]
Whenever i try to install it via brew, it gives me 
```
Downloading https://ghcr.io/v2/catppuccin/tap/catwalk/manifests/1.2.0-1
curl: (22) The requested URL returned error: 401
```
and i have been advised by hammy to open an issue about this
<img width="902" alt="image" src="https://github.com/catppuccin/homebrew-tap/assets/29279972/4fee8ffb-7ca3-4e48-bea4-3fa7baeffa24">

**Comment by uncenter** [comment]
What is your Homebrew version (`brew --version`)?

**Comment by backwardspy** [comment]
hey @GenShibe thanks for raising this! the taps were made private by mistake.

whiskers, catwalk, and mdbook-catppuccin are now public and i'm able to install all three successfully. let me know if you have any further trouble with them.
