### ISSUE TITLE
update to work with latest upload-artifact action

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/homebrew-tap#14]
i've had to [pin `actions/upload-artifact` to v3](https://github.com/catppuccin/homebrew-tap/commit/dc01180464c37fc2f5b136ab69256fa338479d0b) for now as it does not work on latest due to [a breaking change](https://github.com/actions/upload-artifact/issues/472).

as i understand it, in order to get this to work with the latest version of the action we need to upload the bottles with unique names.

**Comment by backwardspy** [comment]
they should work perfectly for now as i have pinned the affected action to v3.

are you experiencing issues with installation?

**Comment by PoorPocketsMcNewHold** [comment]
It does still try to get the v2 it seems.
```
❯ brew install catppuccin/tap/ctp
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Downloading https://ghcr.io/v2/catppuccin/tap/ctp/manifests/2.0.0-1
curl: (22) The requested URL returned error: 401

==> Fetching catppuccin/tap/ctp
==> Downloading https://ghcr.io/v2/catppuccin/tap/ctp/blobs/sha256:08e0d1a6ab38e9bbf3ad2895986b1cd6c7f12fc0234a4c25eea30e173aebb04d
curl: (22) The requested URL returned error: 401

Error: ctp: Failed to download resource "ctp"
Download failed: https://ghcr.io/v2/catppuccin/tap/ctp/blobs/sha256:08e0d1a6ab38e9bbf3ad2895986b1cd6c7f12fc0234a4c25eea30e173aebb04d
```

**Comment by backwardspy** [comment]
ah, i forgot to say that the `ctp` cli is currently unavailable on brew. the only install option for it right now is a source build as it's unfinished and about to undergo some significant reworking.

apologies for the inconvenience!

**Comment by backwardspy** [comment]
i'm gonna close this for now as pinning upload-artifact to v3 is [what homebrew itself does now](https://github.com/Homebrew/brew/commit/29cf01d4422a49a69e5af0cfb169d939e9f4f5b0).

we can update the workflow(s) when homebrew itself does.
